
#STEP DISTANCES
DISTANCE_STANDARD_STEP = 0.01 #m
DISTANCE_REFINE_STEP = 0.005
MEDIUM_STEP = 0.025
BIG_STEP = 0.08 #m

#GLOBAL DISTANCES
BASE_ZONE_X = 1.5
TARGET_ZONE_X = 3.5 + 0.1 + 0.2 #patch + optimize searching
MAP_LENGHT_X = 5
Y_LIMRIGHT = 0 - 0.2
Y_MIDDLE = 1.5
Y_LIMLEFT = 3 + 0.2
TOLERANCE_DIST = 0.02

DIST_BASE_SEARCH_MAP = 0.6 #from where to search base landing pad

MAX_CTR_Z_MEAS = 7
Z_DETEC_TRESHOLD_SEARCH = 0.05#m 
Z_DETEC_TRESHOLD_UP = 0.035    #tweek this number
Z_DETEC_TRESHOLD_DOWN = 0.02 #tweek this number
SLOWER_SPEED = 0.2
FASTER_SPEED = 0.5
#OVERSHOT_DIST_FAST_DOWN = 0.1 #to measure
OVERSHOT_DIST_SLOW_UP = 0.10  #to measure
BOX_SIZE = 0.3

SECURITY_CTR_MAX_STEP_OFF = 40 # *DISTANCE_STANDART_STEP = 40cm
NB_ELEM_MEAN = 20        #tweek this number

EPSILON_PREC = 0.01

MAX_CRT_PRINT = 20
WAITING_TIME = 0.5
WAITING_TIME_MED = 1
WAITING_TIME_LONG = 1.5
PRESHOOT = 80
OVERSHOOT =1
THRESHOLD_SENSOR = 0.55
THRESHOLD_SENSOR_OVERTAKE = 0.8
THRESHOLD_SENSOR_REFINE_TARGET = 0.4








ZIG_ZAG_MARGIN = 0.28 #m