
DISTANCE_STANDART_STEP = 0.01 #m
BIG_STEP = 0.05 #m

MAX_CTR_Z_MEAS = 7
Z_DETEC_TRESHOLD = 0.03#m 
Z_DETEC_TRESHOLD_UP = 0.03    #tweek this number
Z_DETEC_TRESHOLD_DOWN = 0.025 #tweek this number
SLOWER_SPEED = 0.15
FASTER_SPEED = 0.5
#OVERSHOT_DIST_FAST_DOWN = 0.1 #to measure
OVERSHOT_DIST_SLOW_UP = 0.1  #to measure
FASTER_SPEED = 0.5
BOX_SIZE = 0.3

SECURITY_CTR_MAX_STEP_OFF = 30 # *DISTANCE_STANDART_STEP = 30cm
NB_ELEM_MEAN = 15        #tweek this number

EPSILON_PREC = 0.01

MAX_CRT_PRINT = 20
WAITING_TIME = 0.5
WAITING_TIME_LONG = 1.5
PRESHOOT = 60
OVERSHOOT =20
THRESHOLD_SENSOR = 0.5
TOLERANCE_DIST = 0.05